files/application/saleor/order/urls.py
from django.conf.urls import url

from ..core import TOKEN_PATTERN
from . import views


urlpatterns = [
    url(r'^%s/$' % (TOKEN_PATTERN,), views.details, name='details'),
    url(r'^%s/payment/$' % (TOKEN_PATTERN,),
        views.payment, name='payment'),
    url(r'^%s/payment/(?P<variant>[-\w]+)/$' % (TOKEN_PATTERN,),
        views.start_payment, name='payment'),
    url(r'^%s/cancel-payment/$' % (TOKEN_PATTERN,), views.cancel_payment,
        name='cancel-payment'),
    url(r'^%s/create-password/$' % (TOKEN_PATTERN,),
        views.create_password, name='create-password'),
    url(r'^%s/attach/$' % (TOKEN_PATTERN,),
        views.connect_order_with_user, name='connect-order-with-user'),
]

files/application/saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .wishlist.urls import urlpatterns as wishlist_urls

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^account/', include(registration_urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^search/', include(search_urls, namespace='search')),
    url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^wishlist/', include(wishlist_urls, namespace='wishlist')),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/wishlist/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.user_wishlist, name='user-wishlist'),
    url(r'^public/(?P<token>[a-z0-9-]+?)/$',
        views.public_wishlist, name='public-wishlist'),
    url(r'^item/add/$', views.add_wishlist_item, name='add-item'),
    url(r'^item/(?P<item_pk>\d+?)/delete/$',
        views.delete_wishlist_item, name='item-delete')
]

saleor/wishlist/models.py
from __future__ import unicode_literals

from uuid import uuid4

from django.contrib.postgres.fields import HStoreField
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible, smart_text

from ..core.utils import build_absolute_uri
from ..product.models import Product, ProductVariant
from ..userprofile.models import User


@python_2_unicode_compatible
class Wishlist(models.Model):
    user = models.ForeignKey(User)
    token = models.UUIDField(default=uuid4, editable=False, unique=True)
    public = models.BooleanField(default=False)

    def change_token(self, save=False):
        self.token = uuid4()
        if save:
            self.save(update_fields=['token'])

    def __str__(self):
        return 'Wishlist (%s)' % smart_text(self.user)

    def get_absolute_public_url(self):
        return build_absolute_uri(reverse('wishlist:public-wishlist',
                                          kwargs={'token': self.token}))


@python_2_unicode_compatible
class WishlistItem(models.Model):
    wishlist = models.ForeignKey(Wishlist)
    product = models.ForeignKey(Product)
    variant_object = models.ForeignKey(ProductVariant, null=True)
    attributes = HStoreField(default={})
    watch = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('wishlist', 'product', 'variant_object',
                           'attributes')

    def __str__(self):
        if self.variant:
            return "%s - %s" % (smart_text(self.product),
                                smart_text(self.variant))
        else:
            return "%s" % smart_text(self.product)

    @property
    def variant(self):
        if self.variant_object:
            return self.variant_object
        for variant in self.product.variants.all():
            if variant.attributes == self.attributes:
                self.variant_object = variant
                self.save()
                return variant
        return None


@python_2_unicode_compatible
class WishlistNotification(models.Model):
    wishlist = models.ForeignKey(Wishlist)
    variant = models.ForeignKey(ProductVariant)

    class Meta:
        unique_together = ('wishlist', 'variant')

    def __str__(self):
        return "%s - %s" % (smart_text(self.product),
                            smart_text(self.variant))

saleor/wishlist/forms.py
from __future__ import unicode_literals

from django import forms
from django.utils.translation import pgettext_lazy

from .models import Wishlist

ACCESS_CHOICES = (
    (True, pgettext_lazy('wishlist form', 'Public - anyone with url')),
    (False, pgettext_lazy('wishlist form', 'Private - only you')))


class WishlistSettingsForm(forms.ModelForm):
    generate = forms.BooleanField(initial=False, required=False,
                                  label=pgettext_lazy('wishlist form',
                                                      'Generate new url'))

    class Meta:
        model = Wishlist
        fields = ['public']
        labels = {'public': pgettext_lazy('wishlist form', 'Wishlist access')}
        widgets = {'public': forms.Select(choices=ACCESS_CHOICES)}

    def save(self, commit=True):
        obj = super(WishlistSettingsForm, self).save(commit=False)

        if self.cleaned_data['generate'] and hasattr(obj, 'instance'):
            obj.instance.change_token()
        if commit:
            obj.save()
        return obj

saleor/wishlist/views.py
import json

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy
from django.views.decorators.http import require_POST

from . import utils
from ..core.utils import get_paginator_items
from ..product.models import Product, ProductVariant
from .models import Wishlist, WishlistItem


@login_required
def user_wishlist(request):
    # type: (HttpRequest) -> django.http.HttpResponse
    """
    Get or create user wishlist and redirect into public view list.
    """
    wishlist, created = Wishlist.objects.get_or_create(user=request.user)
    return redirect('wishlist:public-wishlist', token=wishlist.token)


def public_wishlist(request, token):
    # type: (HttpRequest, str) -> HttpResponse
    """
    View with items added to wishlist. If wishlist is private, only it's owner
    can see this page.
    """
    query = Wishlist.objects.all()
    query = query.filter(Q(user__pk=request.user.pk) | Q(public=True))
    wishlist = get_object_or_404(query, token=token)
    items = WishlistItem.objects.all().filter(
        wishlist=wishlist).select_related(
        'product__product_class').prefetch_related(
        'variant_object__stock', 'product__images',
        'product__product_class__variant_attributes__values')
    items_page = get_paginator_items(
        items, settings.PAGINATE_BY, request.GET.get('page'))
    items = utils.wishlist_items_with_availability(
        items_page, discounts=request.discounts,
        local_currency=request.currency)
    ctx = {'wishlist': wishlist, 'items': items, 'items_page': items_page}

    return TemplateResponse(request, 'wishlist/list.html', ctx)


@require_POST
@login_required
def add_wishlist_item(request):
    # type: (HttpRequest) -> JsonResponse
    """
    Ajax view used for adding items to logged in user wishlist.
    """
    variant_pk = request.POST.get('variant')
    if variant_pk:
        variant = get_object_or_404(ProductVariant, pk=variant_pk)
        added = utils.add_variant_to_user_wishlist(request.user, variant)
    else:
        attributes = json.loads(request.POST.get('attributes', "{}"))
        product = get_object_or_404(Product, pk=request.POST.get('product'))
        added = utils.add_to_user_wishlist(request.user, product, attributes)
    if added:
        messages.success(request, pgettext_lazy('wishlist',
                                                'New item added into list'))
        return JsonResponse(status=201, data={})
    messages.info(request, pgettext_lazy('wishlist',
                                         'Item already in wishlist'))
    return JsonResponse(data={})


@login_required
def delete_wishlist_item(request, item_pk):
    # type: (HttpRequest, str) -> HttpResponse
    """
    View used for removing items from user wishlist.
    """
    item = get_object_or_404(WishlistItem.objects.filter(
        wishlist__user=request.user), pk=item_pk)
    if request.method == 'POST':
        item.delete()
        messages.success(request, pgettext_lazy('wishlist',
                                                'Item removed from list'))
        return redirect('wishlist:user-wishlist')
    ctx = {'item': item,
           'item_name': '%s - %s' % (item.product,
                                     utils.wishlist_item_variant_name(item))}
    return TemplateResponse(
        request, 'wishlist/modal_delete.html', ctx)

templates/wishlist/_items.html
{% load i18n %}
{% load staticfiles %}
{% load price_range from price_ranges %}
{% load product_first_image from product_images %}

{% for item, availability in items %}
  <div class="col-xs-6 col-md-4 product-list" itemscope itemtype="https://schema.org/Product">
    <div class="text-center">
      <div>
        <a itemprop="url" href="{{ item.url }}">
          <img itemprop="image" class="img-responsive" src="{% product_first_image item.product method="crop" size="400x400" %}" alt="">
          <span class="product-list-item-name" itemprop="name" title="{{ item.product }}">{{ item.product }}<br>{{ item.variant_name }}</span>
        </a>
      </div>
      <div>
      {% if availability.available %}
        {% price_range availability.price_range %}
        {% if availability.discount %}
          {% if undiscounted.min_price != price_range.min_price %}
          <div class="product-list__sale"><span>{% trans "Sale" context "wishlist" %}</span></div>
          {% endif %}
        {% endif %}
      {% else %}
      &nbsp;
      {% endif %}
        <p>
          <a href="#base-modal" data-href="{{ item.delete_url }}"
             class="modal-trigger-custom">{% trans "Remove" context "wishlist" %}</a>
        </p>
      </div>
    </div>
  </div>
{% endfor %}

templates/wishlist/list.html
{% extends "base.html" %}
{% load i18n %}
{% load slice from shop %}
{% load static from staticfiles %}
{% load bootstrap_pagination from bootstrap3 %}
{% load product_first_image from product_images %}
{% load price_range from price_ranges %}


{% block title %}Wishlist — {{ block.super }}{% endblock %}

{% block breadcrumb %}
  {{ block.super }}
  {% for breadcrumb in breadcrumbs %}
    <li{% if forloop.last %} class="active"{% endif %}>
    {% if not forloop.last %}
      <a href="{{ breadcrumb.get_absolute_url }}">{{ breadcrumb }}</a>
    {% else %}
      <span>{{ breadcrumb }}</span>
    {% endif %}
  </li>
  {% endfor %}
{% endblock breadcrumb %}

{% block content %}
  <h1>{% trans 'Wishlist' context "wishlist" %}</h1>
  {% if wishlist.user == user %}
  <p>
    {% trans "Change settings of your wishlist" context "wishlist" %} <a href="{% url "profile:details" %}#wishlist">{% trans "here" context "wishlist" %}</a>.
  </p>
  {% endif %}
  <div>
    <div class="row">
      {% include "wishlist/_items.html" %}
    </div>
    {% if items_page.has_other_pages %}
    {% bootstrap_pagination items_page %}
    {% endif %}
  </div>
  <div class="modal fade" id="base-modal" tabindex="-1" role="dialog" ></div>
{% endblock content %}

templates/wishlist/modal_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load slice from shop %}
{% load static from staticfiles %}
{% load bootstrap_pagination from bootstrap3 %}
{% load product_first_image from product_images %}
{% load price_range from price_ranges %}


{% block title %}Wishlist — {{ block.super }}{% endblock %}

{% block breadcrumb %}
  {{ block.super }}
  {% for breadcrumb in breadcrumbs %}
    <li{% if forloop.last %} class="active"{% endif %}>
    {% if not forloop.last %}
      <a href="{{ breadcrumb.get_absolute_url }}">{{ breadcrumb }}</a>
    {% else %}
      <span>{{ breadcrumb }}</span>
    {% endif %}
  </li>
  {% endfor %}
{% endblock breadcrumb %}

{% block content %}
  <h1>{% trans 'Wishlist' context "wishlist" %}</h1>
  {% if wishlist.user == user %}
  <p>
    {% trans "Change settings of your wishlist" context "wishlist" %} <a href="{% url "profile:details" %}#wishlist">{% trans "here" context "wishlist" %}</a>.
  </p>
  {% endif %}
  <div>
    <div class="row">
      {% include "wishlist/_items.html" %}
    </div>
    {% if items_page.has_other_pages %}
    {% bootstrap_pagination items_page %}
    {% endif %}
  </div>
  <div class="modal fade" id="base-modal" tabindex="-1" role="dialog" ></div>
{% endblock content %}